[package]
name = "textos"
description = "text stuff"
version = "0.0.0"
edition = "2021"
rust-version = "1.67.1"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/textos"
documentation = "https://docs.rs/textos"
license = "MIT/Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/LICENSE-*",
	"/README.md",
]
categories = []
keywords = []
publish = false

[dependencies]
paste = "1.0.11"

[features]
default = ["std", "safe"]
safe = []
std = []
nightly = []
doc = ["std", "nightly"]

[dev-dependencies]

[package.metadata.docs.rs]
default-features = false
features = ["doc"]

[badges]
maintenance = { status = "experimental" }
